apiVersion: apps/v1
kind: Deployment
metadata:
  name: clamav
  namespace: {{ .Values.namespace }}
  labels:
    app: clamav
spec:
  replicas: 1
  selector:
    matchLabels:
      app: clamav
  template:
    metadata:
      labels:
        app: clamav
    spec:
      containers:
      - name: clamav
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        env:
        - name: CLAMAV_NO_FRESHCLAM
          value: "{{ .Values.environment.noFreshclam }}"
        ports:
        - name: clamav
          containerPort: {{ .Values.service.port }}
          protocol: TCP
        volumeMounts:
        - name: clamav-db
          mountPath: /var/lib/clamav
        {{- if .Values.config.enabled }}
        - name: config
          mountPath: /etc/clamav/clamd.conf
          subPath: clamd.conf
          readOnly: true
        {{- end }}
        livenessProbe:
          exec:
            command:
              - /usr/local/bin/clamdcheck.sh
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
          failureThreshold: {{ .Values.healthcheck.failureThreshold }}
        readinessProbe:
          exec:
            command:
              - /usr/local/bin/clamdcheck.sh
          initialDelaySeconds: {{ .Values.healthcheck.initialDelaySeconds }}
          periodSeconds: {{ .Values.healthcheck.periodSeconds }}
          timeoutSeconds: {{ .Values.healthcheck.timeoutSeconds }}
        resources:
          requests:
            memory: {{ .Values.resources.requests.memory }}
            cpu: {{ .Values.resources.requests.cpu }}
          limits:
            memory: {{ .Values.resources.limits.memory }}
            cpu: {{ .Values.resources.limits.cpu }}
      volumes:
      - name: clamav-db
        persistentVolumeClaim:
          claimName: clamav-db
      {{- if .Values.config.enabled }}
      - name: config
        configMap:
          name: clamav-config
      {{- end }}
