services:
  api:
    build: "./"
    restart: "always"
    container_name: "buerokratt-storage-ferry"
    ports:
      - 3000:3000
    env_file:
      - config/development.env
    volumes:
      - ./data:/api/data
    environment:
      - S3_ENDPOINT_URL=http://localstack:4566
  localstack:
    image: localstack/localstack:3.3.0
    ports:
      - 4566:4566
    environment:
      - SERVICES=s3:4566
    volumes:
      # This creates a test bucket
      # Not strictly necessary if using test-driven approach for development
      # Tests are configured in a way that they create the containers themselves
      # But this is useful as an example that can be used in other repos
      - ./scripts/localstack-init.sh:/etc/localstack/init/ready.d/init.sh
  azurite:
    image: mcr.microsoft.com/azure-storage/azurite:latest
    ports:
      - 10000:10000
      - 10001:10001
      - 10002:10002
    environment:
      - AZURITE_ACCOUNTS=testaccount1:dGVzdGtleTE9PQ==;testaccount2:dGVzdGtleTI9PQ==;testaccount3:dGVzdGtleTM9PQ==
    volumes:
      - azurite-data:/data
  # This creates a test container
  # Not strictly necessary if using test-driven approach for development
  # Tests are configured in a way that they create the containers themselves
  # But this is useful as an example that can be used in other repos
  azurite-init:
    image: node:24-alpine
    depends_on:
      - azurite
    volumes:
      - ./scripts:/scripts:ro
    entrypoint: /bin/sh
    command: -c "/scripts/azurite-init.sh"
volumes:
  azurite-data:
