# Network
TCPSocket 3310
TCPAddr 0.0.0.0

# User/Group
User clamav

# STREAMING LIMITS
StreamMaxLength 500M
MaxFileSize 500M
MaxScanSize 500M

# ARCHIVES
MaxRecursion 16
MaxFiles 10000
MaxDirectoryRecursion 15

# PERFORMANCE
MaxThreads 6
MaxConnectionQueueLength 30

# TIMEOUTS
CommandReadTimeout 600
ReadTimeout 600
SendBufTimeout 500

# LOGGING
LogTime yes
LogClean yes
LogVerbose yes
ExtendedDetectionInfo yes
LogFileMaxSize 10M
LogFile /var/log/clamav/clamd.log

# DATABASE
DatabaseDirectory /var/lib/clamav

# DAEMON
Foreground yes

