apiVersion: v1
kind: Service
metadata:
  name: nats
  namespace: { { .Values.namespace } }
  labels:
    app: nats
spec:
  type: { { .Values.service.type } }
  ports:
    - name: client
      port: { { .Values.service.clientPort } }
      targetPort: client
      protocol: TCP
    - name: monitoring
      port: { { .Values.service.monitoringPort } }
      targetPort: monitoring
      protocol: TCP
  selector:
    app: nats
