namespace: buerokratt

image:
  repository: minio/minio
  tag: latest
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  apiPort: 9000
  consolePort: 9001

credentials:
  rootUser: minioadmin
  rootPassword: minioadmin

storage:
  size: 10Gi
  storageClass: ''

buckets:
  - quarantined
  - validated
  - flagged

resources:
  requests:
    memory: '512Mi'
    cpu: '250m'
  limits:
    memory: '1Gi'
    cpu: '500m'

initJob:
  enabled: true
  image:
    repository: minio/mc
    tag: latest
    pullPolicy: IfNotPresent
